export const LOAD_MUSICS_START="LOAD_MUSICS_START"
export const LOAD_MUSICS_SUCCESS="LOAD_MUSICS_SUCCESS"
export const LOAD_MUSICS_ERROR="LOAD_MUSICS_ERROR"


export const CREATE_MUSICS_START="CREATE_MUSICS_START"
export const CREATE_MUSICS_SUCCESS="CREATE_MUSICS_SUCCESS"
export const CREATE_MUSICS_ERROR="CREATE_MUSICS_ERROR"


export const DELETE_MUSICS_START="DELETE_MUSICS_START"
export const DELETE_MUSICS_SUCCESS="DELETE_MUSICS_SUCCESS"
export const DELETE_MUSICS_ERROR="DELETE_MUSICS_ERROR"

export const UPDATE_MUSICS_START="UPDATE_MUSICS_START"
export const UPDATE_MUSICS_SUCCESS="UPDATE_MUSICS_SUCCESS"
export const UPDATE_MUSICS_ERROR="UPDATE_MUSICS_ERROR"